// Generated by CoffeeScript 1.6.3
var Parser, Serializer, parse, stringify;

Parser = require('./parser');

Serializer = require('./serializer');

parse = function(text, reviver) {
  return new Parser({
    empty: false
  }).process(text);
};

stringify = function(data, replacer, space) {
  return new Serializer(replacer, space).process(data);
};

module.exports = {
  parse: parse,
  stringify: stringify
};
