// Generated by CoffeeScript 1.6.2
var Loader;

Loader = {
  handler: function(module) {
    module.exports = {
      test: true
    };
    return void 0;
  },
  register: function() {
    require.extensions['.xml'] = this.handler;
    return void 0;
  }
};

module.exports = Loader;
