// Generated by CoffeeScript 1.6.3
var Parser, Reader;

Reader = require('./reader');

Parser = (function() {
  function Parser() {}

  Parser.prototype._onOpenTag = function(name) {
    return this._object[name] = null;
  };

  Parser.prototype._onCloseTag = function(name) {};

  Parser.prototype._onText = function(value) {};

  Parser.prototype._onPI = function(target, value) {
    return this._object.$pi = null;
  };

  Parser.prototype._onComment = function(value) {
    return this._object.$text = null;
  };

  Parser.prototype.process = function(text) {
    this._data = {};
    return this._object = {};
  };

  return Parser;

})();

module.exports = Parser;
