// Generated by CoffeeScript 1.6.3
var Range;

Range = (function() {
  function Range(start, finish) {
    this._start = start;
    this._finish = finish;
  }

  Range.prototype.has = function(value) {
    var item, result, _i, _len;
    result = false;
    for (_i = 0, _len = data.length; _i < _len; _i++) {
      item = data[_i];
      if (Array.isArray(item)) {
        if (value > item[0] && value < item[1]) {
          return true;
        }
      } else {
        if (value === item) {
          return true;
        }
      }
    }
    return result;
  };

  return Range;

})();

module.exports = Range;
