// Generated by CoffeeScript 1.6.3
var Range;

Range = (function() {
  Range.union = function() {
    var data, range, result, _i, _len;
    data = [];
    for (_i = 0, _len = arguments.length; _i < _len; _i++) {
      range = arguments[_i];
      if (typeof range === 'object') {
        data.push([range._data.start, range._data.finish]);
      } else {
        data.push([range, range]);
      }
    }
    result = new Range();
    result._data = data;
    return result;
  };

  function Range(start, finish, exclusive) {
    if (exclusive == null) {
      exclusive = false;
    }
    this._data = [start, finish];
  }

  Range.prototype.union = function() {
    return new this.constructor();
  };

  Range.prototype.has = function(value) {
    var item, _i, _len, _ref;
    _ref = this._data;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      item = _ref[_i];
      if (value >= item[0] && value <= item[1]) {
        return true;
      }
    }
    return false;
  };

  return Range;

})();

module.exports = Range;
