// Generated by CoffeeScript 1.6.2
var EventEmitter, Reader, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

EventEmitter = require('events').EventEmitter;

Reader = (function(_super) {
  __extends(Reader, _super);

  function Reader() {
    _ref = Reader.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  return Reader;

})(EventEmitter);

module.exports = Reader;
