// Generated by CoffeeScript 1.6.2
var Serializer;

Serializer = (function() {
  function Serializer(data) {
    this.data = data;
  }

  Serializer.prototype.writeAttribute = function(key, value) {
    this.buffer.push(' ' + key + '="' + value + '"');
    return this;
  };

  Serializer.prototype.writeElement = function(key, value) {
    if (typeof value === 'object') {
      value = value.valueOf();
    }
    if (typeof value === 'object') {
      this.buffer.push('<', key, '>');
      this.stringifyObject(value);
      this.buffer.push('</', key, '>');
    } else {
      this.buffer.push('<' + key + '>', value, '</' + key + '>');
    }
    return this;
  };

  Serializer.prototype.inspect = function() {
    return this.toString();
  };

  Serializer.prototype.toString = function() {
    this.buffer = ['<?xml version="1.0"?>'];
    this.stringifyObject(this.data);
    return this.buffer.join('');
  };

  return Serializer;

})();

module.exports = Serializer;
