// Generated by CoffeeScript 1.6.2
var Writer;

Writer = (function() {
  function Writer(stream) {}

  Writer.prototype.startElement = function(key) {
    this.buffer.push('<' + key + '>');
    return this;
  };

  Writer.prototype.endElement = function(key) {
    this.buffer.push('</' + key + '>');
    return this;
  };

  Writer.prototype.pushElement = function(key, value) {
    return this;
  };

  Writer.prototype.pushAtrribute = function(key, value) {
    return this;
  };

  Writer.prototype.pushText = function(value) {
    return this;
  };

  Writer.prototype.pushComment = function(value) {
    return this;
  };

  return Writer;

})();

module.exports = Writer;
