// Generated by CoffeeScript 1.6.3
var Writer;

Writer = (function() {
  function Writer(options) {
    this._buffer = [];
    this._empty = null;
  }

  Writer.prototype.startElement = function(name) {
    if (this._empty) {
      this._buffer.push('>');
    }
    this._buffer.push('<', name);
    this._empty = true;
    return this;
  };

  Writer.prototype.endElement = function(name) {
    if (this._empty) {
      this._buffer.push('/>');
    } else {
      this._buffer.push('</', name, '>');
    }
    return this;
  };

  Writer.prototype.pushAttribute = function(name, value) {
    this._buffer.push(' ', name, '="', value, '"');
    return this;
  };

  Writer.prototype.pushElement = function(name, value) {
    if (this._empty) {
      this._buffer.push('>');
    }
    this._empty = false;
    this._buffer.push('<', name, '>', value, '</', name, '>');
    return this;
  };

  Writer.prototype.pushText = function(value) {
    if (this._empty) {
      this._buffer.push('>');
    }
    this._empty = false;
    this._buffer.push(value);
    return this;
  };

  Writer.prototype.pushSection = function(value) {
    if (this._empty) {
      this._buffer.push('>');
    }
    this._empty = false;
    this._buffer.push('<![CDATA[', value, ']]>');
    return this;
  };

  Writer.prototype.pushComment = function(value) {
    if (this._empty) {
      this._buffer.push('>');
    }
    this._empty = false;
    this._buffer.push('<!--', value, '-->');
    return this;
  };

  Writer.prototype.result = function() {
    return this._buffer.join('');
  };

  return Writer;

})();

module.exports = Writer;
