// Generated by CoffeeScript 1.6.2
var Reader, Writer, XML;

Reader = require('./reader');

Writer = require('./writer');

XML = {
  parse: function(text, reviver) {},
  stringify: function(data, replacer, space) {
    return new Standard(data).toString();
  }
};

Object.defineProperties(XML, {
  parse: {
    enumerable: false
  },
  stringify: {
    enumerable: false
  }
});

module.exports = XML;
