// Generated by CoffeeScript 1.6.2
var Standard, XML;

Standard = require('./standard');

XML = {
  parse: function(string, reviver) {},
  stringify: function(data, replacer, space) {
    return new Standard(data).toString();
  }
};

Object.defineProperties(XML, {
  parse: {
    enumerable: false
  },
  stringify: {
    enumerable: false
  }
});

module.exports = XML;
